#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Preparing to commit: Formatting, testing, and building your project...'

# Check Lint
yarn run lint ||
(
        echo '😤🏀👋😤 Lint Check Failed! 🙅‍♂️
                Make the required changes listed above, add the changes, and try to commit again.'
        false; 
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... All good! Committing now. 🚀'
